[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "evo_opt"
version = "0.1.0"
description = "My evo optimization tools"
requires-python = ">=3.11"
dependencies = [
    "numpy",
    "cma",
    "PyYAML",
]

[tool.setuptools]
packages = ["evo_opt"]

[project.scripts]
exptoinp   = "evo_opt.exp_to_inp_tool:main"
expcomp    = "evo_opt.exp_compare_tool:main"
exptoexpo  = "evo_opt.exp_to_expo_tool:main"
expevo     = "evo_opt.exp_evo_tool:cli"
cmafex     = "evo_opt.cma_fex_tool:cli"